# Generated by Django 3.2.7 on 2021-09-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massiliarp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainablebuilding',
            name='number_built',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number built'),
        ),
        migrations.AddField(
            model_name='profitablebuilding',
            name='number_built',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number built'),
        ),
    ]
