# Generated by Django 3.2.7 on 2021-09-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massiliarp', '0002_auto_20210925_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armyunit',
            name='recruitment_cost',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Recruitment cost'),
        ),
        migrations.AlterField(
            model_name='armyunit',
            name='upkeep_cost',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Unit upkeep'),
        ),
        migrations.AlterField(
            model_name='navyunit',
            name='recruitment_cost',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Recruitment cost'),
        ),
        migrations.AlterField(
            model_name='navyunit',
            name='upkeep_cost',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Unit upkeep'),
        ),
    ]
