# Generated by Django 3.2.7 on 2021-09-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massiliarp', '0003_auto_20210925_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armyunit',
            name='upkeep_cost',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Unit upkeep'),
        ),
        migrations.AlterField(
            model_name='navyunit',
            name='upkeep_cost',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Unit upkeep'),
        ),
    ]
