# Generated by Django 3.2.8 on 2021-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massiliarp', '0005_rename_turn_balancesheet_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueevent',
            name='year',
            field=models.PositiveSmallIntegerField(default=298, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='uniqueevent',
            unique_together={('name', 'year')},
        ),
        migrations.RemoveField(
            model_name='uniqueevent',
            name='turn',
        ),
    ]
